### ISSUE TITLE
new

### ISSUE THREAD

**Issue by caiyinqiong** [caiyinqiong/Semantic-Retrieval-Models#2]
Questions Are All You Need to Train a Dense Passage Retriever（zero-shot）
HypeR: Multitask Hyper-Prompted Training Enables Large-Scale Retrieval Generalization（ICLR2023，zero-shot）
COCO-DR: Combating Distribution Shifts in Zero-Shot Dense Retrieval with Contrastive and Distributionally Robust Learning (EMNLP2022, zero-shot)

**Comment by caiyinqiong** [comment]
An Encoder Attribution Analysis for Dense Passage Retriever in Open-Domain Question Answering(other)

**Comment by caiyinqiong** [comment]
Sentence-aware Contrastive Learning for Open-Domain Passage Retrieval（DCSR，dense retrieval）
Task-Aware Specialization for Efﬁcient and Robust Dense Retrieval for Open-Domain Question Answering（TASER，dense retrieval）

**Comment by caiyinqiong** [comment]
IntTower: the Next Generation of Two-Tower Model for Pre-Ranking System（inject interaction）

**Comment by caiyinqiong** [comment]
Parameter-Efﬁcient Prompt Tuning Makes Generalized and Calibrated Neural Text Retrievers（prompt learning）

**Comment by drogozhang** [comment]
Thanks for the comprehensive and well-curated paper list!
[LED: Lexicon-Enlightened Dense Retriever for Large-Scale Retrieval](https://arxiv.org/pdf/2208.13661.pdf) has been accepted to WWW'23.

**Comment by caiyinqiong** [comment]
@drogozhang  Great job, congratulations! I will update the information in this repository~

**Comment by drogozhang** [comment]
@caiyinqiong Thanks!!

**Comment by caiyinqiong** [comment]
RetroMAE: Pre-Training Retrieval-oriented Language Models Via Masked Auto-Encoder(pre-training, EMNLP2022)
Retrieval Oriented Masking Pre-training Language Model for Dense Passage Retrieval (pre-training)

**Comment by tshu-w** [comment]
> RetroMAE: Pre-Training Retrieval-oriented Language Models Via Masked Auto-Encoder(pre-training, EMNLP2022)

RetroMAE is duplicated in the list, and the author of the first one may be wrong.

**Comment by caiyinqiong** [comment]
@tshu-w  I have corrected the errors above. Thank you for your attention to this repository~
